### ISSUE TITLE
Not Updating

### ISSUE THREAD

**Issue by sylon412** [zevnda/steam-game-idler#108]
### Pre-report Checklist

- [x] I have searched for similar [open/closed issues](https://github.com/zevnda/steam-game-idler/issues)
- [x] I have checked the [FAQ page](https://steamgameidler.vercel.app/faq) for my issue

### Issue Description

After i update from 1.7.21 to 1.8. (via the in app funktion) after a restart of the prgram its back to 1.7.21.

### Steps to Reproduce

After i update from 1.7.21 to 1.8. after a restort of the prgram its back to 1.7.21.

### Log File

Mar 13 10:22:19.281 + [v1.7.21] [System] Updated Steam Game Idler (1.7.21 > 1.8.0)
Mar 13 10:03:39.206 + [v1.7.21] [System] Updated Steam Game Idler (1.7.21 > 1.8.0)
Mar 13 10:03:08.666 + [v1.7.21] [System] Updated Steam Game Idler (1.7.21 > 1.8.0)
Mar 13 00:41:48.757 + [v1.7.21] [Idle] Started idling The First Descendant (2074920)
Mar 12 11:49:00.917 + [v1.7.21] [Idle] Started idling The First Descendant (2074920)
Mar 12 11:46:43.211 + [v1.7.21] [Idle] Started idling FragPunk (2943650)
Mar 12 11:07:41.240 + [v1.7.21] [Idle] Started idling The First Descendant (2074920)
Mar 12 00:16:34.353 + [v1.7.21] [Idle] Started idling The First Descendant (2074920)
Mar 11 12:05:22.286 + [v1.7.24] [Idle] Started idling The First Descendant (2074920)
Mar 11 12:04:54.364 + [v1.7.21] [System] Updated Steam Game Idler (1.7.21 > 1.7.24)
Mar 11 11:24:29.802 + [v1.7.24] [Error] in (handleResetSettings): TypeError: r is not a function
Mar 11 11:23:17.756 + [v1.7.21] [System] Updated Steam Game Idler (1.7.21 > 1.7.24)
Mar 11 11:23:11.973 + [v1.7.21] [Idle] Started idling The First Descendant (2074920)
Mar 11 00:27:06.249 + [v1.7.21] [System] Updated Steam Game Idler (1.7.21 > 1.7.24)
Mar 11 00:26:56.843 + [v1.7.21] [Idle] Started idling The First Descendant (2074920)
Mar 10 12:15:27.942 + [v1.7.23] [Idle] Started idling The First Descendant (2074920)
Mar 10 12:15:13.932 + [v1.7.23] [Error] in (checkForFreeGames): TypeError: Cannot read properties of undefined (reading 'length')
Mar 10 12:15:13.931 + [v1.7.23] [Error] in (fetchFreeGames): error sending request for url (https://store.steampowered.com/search/?l=english&maxprice=free&specials=1)
Mar 10 12:15:07.621 + [v1.7.21] [System] Updated Steam Game Idler (1.7.21 > 1.7.23)
Mar 10 12:14:57.430 + [v1.7.21] [Idle] Started idling The First Descendant (2074920)
Mar 09 14:31:08.742 + [v1.7.21] [Idle] Started idling The First Descendant (2074920)
Mar 09 14:27:20.441 + [v1.7.21] [System] Logged in as SyLoN | trackartelier.de

### Exported Data

```json
{
  "version": "1.7.21",
  "lastNotifiedTimestamp": 1741613142986,
  "settings": {
    "general": {
      "stealthIdle": false,
      "antiAway": false,
      "clearData": true,
      "freeGameNotifications": true
    },
    "cardFarming": {
      "listGames": true,
      "allGames": false
    },
    "achievementUnlocker": {
      "idle": true,
      "hidden": false,
      "schedule": false,
      "scheduleFrom": {
        "hour": 8,
        "minute": 30,
        "second": 0,
        "millisecond": 0
      },
      "scheduleTo": {
        "hour": 23,
        "minute": 0,
        "second": 0,
        "millisecond": 0
      },
      "interval": [
        30,
        130
      ]
    }
  },
  "theme": "light",
  "notificationsCooldown": 1741858383031,
  "minToTrayNotified": true,
  "sortStyle": "1-0",
  "favoritesListCache": [
    {
      "appid": 2074920,
      "name": "The First Descendant"
    }
  ]
}
```

**Comment by zevnda** [comment]
There have been quite a few major updates since `1.7.21`, including to the installer. I migrated from using the MSI `.msi` installer to using NSIS `.exe` installer in `1.7.23`, which could have potential issues when updating.

You might need to manually uninstall the current version, and [download the `1.8.0` installer here](https://github.com/zevnda/steam-game-idler/releases/latest).

Let me know if you have any other questions.
